---
codecov:
  notify:
    require_ci_to_pass: true
coverage:
  precision: 2
  round: down
  range: 60...100
  status:
    patch:
      default:
        target: 70%
    project:
      default:
        target: 90%
ignore:
  - setup.py
  - tests/*
  - tests/**/*
  - .tox/**/*
  - src/toy_models/*
  - src/dcegm/likelihood.py
  - src/dcegm/wealth_correction.py
  - src/dcegm/interface.py
