---
name: rtd_dcegm
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pip
  - ipython
  - jupyter
  - myst-nb
  - numpydoc
  - sphinx
  - sphinx-autobuild
  - sphinx-autoapi
  - sphinx-design
  - sphinx-copybutton
  - pip:
      - sphinx-tabs
      - furo
